### PR TITLE
new function to plot voter shares of single surveys

### PR DESCRIPTION
**Pull request by bauer-alex**

### CODE REVIEW

**Comment by adibender** [comment]
image
All checks have failed

**Comment by bauer-alex** [comment]
next try

**Comment by bauer-alex** [comment]
Kennst du den AppVeyor-Fehler? Sieht mir iwie nicht so aus als wär mein neuer Code der Grund dafür...

**Comment by adibender** [comment]
ja, appveyour ist da manchmal etwas strange wenn es um code geht der internet connection braucht. Einfach ignorieren

**Comment by adibender** [comment]
hm, somehow your branch doesn't have vignettes, data-raw, paper folders ... ? Have you merged the current master into your fork?

**Comment by bauer-alex** [comment]
I did merge the current master into the fork and I do have the data-raw, vignettes folder etc.
As far as I see it there shouldn't be any problem with the merge.

**Comment by bauer-alex** [comment]
Maybe you referred to the devel branch of my fork? Actually yeah, this isn't up to date. But for this PR I worked on my forks' master branch.

**Review by adibender — CHANGES_REQUESTED** [review]
My preference w.r.t. convenience ploting functions is 
a) have a user-visible function that creates and returns the data used for plotting
b) have a custom convenience function that creates the plot (but now options for customization

Then, they can use a) to create a plot they want from scratch or use b) to customize labels, etc. of the returned ggplot2 object. 

Also I'd prefer to 
- name all plotting functions `gg_*`
- remove all style options. The convenience plot is for exploration only anyway, in most cases user will want to modify it in ways we cannot anticipate, so why bother 
- function arguments should each on a separate row, e.g. 
```r 
draw_from_posterior <- function(
  survey,
  nsim       = 1e4,
  seed       = as.numeric(now()),
  prior      = NULL,
  correction = NULL) {
  
  ...

}
```
- put assertions at the top of each exported function, i.e. `assert_data_frame(data)`

- I think it would be a good idea to store `cols` and `labels` that are often used as objects in the package and use them as defaults, e.g. : 
```r
gg_survey(
data, 
cols = cols_de,
... ) {
... 
}
```
where cols_de is stored internally 

- Code/roxygen comments should not go beyond 80 character line

**Comment by adibender** [comment]
yeah, you should always synchronize with the current master of the original repository

**Comment by bauer-alex** [comment]
Requested changes are now included

**Comment by adibender** [comment]
close in favor of #111

**Pull request closed without merging**
